name: Upload Assets
on:
  release:
    types: [published]

jobs:
  build:
    name: Upload Assets
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./scripts/xcframework.sh -output ProtocolProxy.xcframework

    - name: Create Zip
      run: |
        zip -rX ProtocolProxy.xcframework.zip ProtocolProxy.xcframework

    - name: Upload Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./ProtocolProxy.xcframework.zip
        asset_name: ProtocolProxy.xcframework.zip
        asset_content_type: application/zip

    - name: Create Tar
      run: |
        tar -zcvf ProtocolProxy.xcframework.tar.gz ProtocolProxy.xcframework

    - name: Upload Tar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./ProtocolProxy.xcframework.tar.gz
        asset_name: ProtocolProxy.xcframework.tar.gz
        asset_content_type: application/gzip
