name: XCFramework
on: push

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
      TMPDIR: /tmp/.protocolproxy.xcframework.build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./scripts/xcframework.sh -output ${TMPDIR}/${GITHUB_SHA}/ProtocolProxy.xcframework
