name: XCFramework
on: push

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
      TMPDIR: /tmp/.protocolproxy.xcframework.build.${GITHUB_SHA}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        ./scripts/xcframework.sh -output ${TMPDIR}/ProtocolProxy.xcframework
