name: Build Xcode Project
on: push

jobs:
  ios:
    name: iOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build iOS
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy" -sdk iphoneos -configuration Debug ONLY_ACTIVE_ARCH=YES

    - name: Build iOS Simulator
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy" -sdk iphonesimulator -configuration Debug ONLY_ACTIVE_ARCH=YES

    - name: Test
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max" -configuration Debug ONLY_ACTIVE_ARCH=YES test

  maccatalyst:
    name: Mac Catalyst
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy" -sdk macosx -configuration Debug ONLY_ACTIVE_ARCH=YES

    - name: Test
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy" -destination "platform=macOS" -configuration Debug ONLY_ACTIVE_ARCH=YES test

  macos:
    name: macOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy macOS" -configuration Debug ONLY_ACTIVE_ARCH=YES

    - name: Test
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy macOS" -configuration Debug ONLY_ACTIVE_ARCH=YES test

  tvos:
    name: tvOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build tvOS
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy tvOS" -sdk appletvos -configuration Debug ONLY_ACTIVE_ARCH=YES

    - name: Build tvOS Simulator
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy tvOS" -sdk appletvsimulator -configuration Debug ONLY_ACTIVE_ARCH=YES

    - name: Test
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy tvOS" -destination "platform=tvOS Simulator,name=Apple TV 4K" -configuration Debug ONLY_ACTIVE_ARCH=YES test

  watchos:
    name: watchOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build watchOS
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy watchOS" -sdk watchos -configuration Debug

    - name: Build watchOS Simulator
      run: |
        xcodebuild -project ProtocolProxy.xcodeproj -scheme "ProtocolProxy watchOS" -sdk watchsimulator -configuration Debug
